// Copyright 2024 - NegativeNameSeller

#pragma once

#include "CoreMinimal.h"
#include "Core/OpenLogicTypes.h"

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_OpenLogicDefaultLibrary)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_OpenLogicEventLibrary)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_OpenLogicFlowControlLibrary)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_OpenLogicUtilityLibrary)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_OpenLogicLiteralLibrary)